version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "account"
      - "machama"
      - "messaging"
      - "subscriber"
      - "channel"
      - "sms"
      
  mysql:
    container_name: mysql
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/gideon/mysql-storage/machama-prod/:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: hakty11
      MYSQL_ROOT_PASSWORD: hakty11
      MYSQL_DATABASE: machama

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  machama:
    container_name: machama
    image: gidyon/machama-app:latest
    command: ["--config-file", "/app/configs/config.yml"]
    depends_on:
      - "mysql"
    deploy:
      replicas: 1
    volumes:
      - ./configs/machama.config.yaml:/app/configs/config.yml
    environment:
      JWT_SIGNING_KEY: QFyvRWu7CeoHl6VS54ACvc27B7acfKCYWRLz7T8vSyBMOUA3VbKG9G1nLgsOmV9gryrTlkpKN357fcM0C81NsJ0ROHa4Jx8ps

  account:
    container_name: account
    image: gidyon/account:v2
    command: ["--config-file", "/app/configs/config.yml"]
    depends_on:
      - "mysql"
    deploy:
      replicas: 1
    volumes:
      - ./configs/account.config.yaml:/app/configs/config.yml
      - ./templates/:/app/templates
      - ./secrets/mvasltd-firebase-adminsdk.json:/app/secrets/firebase.creds.json
    environment:
      APP_NAME: Accounts API
      EMAIL_DISPLAY_NAME: Accounts API
      TEMPLATES_DIR: /app/templates
      ACTIVATION_URL: https://ldaddress/activate
      FIREBASE_CREDENTIALS_FILE: /app/secrets/firebase.creds.json
      JWT_SIGNING_KEY: QFyvRWu7CeoHl6VS54ACvc27B7acfKCYWRLz7T8vSyBMOUA3VbKG9G1nLgsOmV9gryrTlkpKN357fcM0C81NsJ0ROHa4Jx8ps
      API_HASH_KEY: hmpVpI2nyiMhYIqLQlNfcL6QD37IOX1CklyU6TmVTy8hfbhblYUnKrHh4S93S2zORhmF2E3e6xDMLH5Dps0lM8XCQsV8cSP
      API_BLOCK_KEY: PLTUTCo256Cg84A4lgZpa6mLsMqsX5qZzHTbD3Q2YbbRm5dejA9NGIufbhHkHcbjrPCsNt89W

  messaging:
    container_name: messaging
    image: gidyon/messaging:v2
    command: ["--config-file", "/app/configs/config.yml"]
    depends_on:
      - "mysql"
    deploy:
      replicas: 1
    volumes:
      - ./configs/messaging.config.yaml:/app/configs/config.yml
    environment:
      SENDER_EMAIL_ADDRESS: gideonhacer@gmail.com
      JWT_SIGNING_KEY: QFyvRWu7CeoHl6VS54ACvc27B7acfKCYWRLz7T8vSyBMOUA3VbKG9G1nLgsOmV9gryrTlkpKN357fcM0C81NsJ0ROHa4Jx8ps
      API_HASH_KEY: hmpVpI2nyiMhYIqLQlNfcL6QD37IOX1CklyU6TmVTy8hfbhblYUnKrHh4S93S2zORhmF2E3e6xDMLH5Dps0lM8XCQsV8cSP
      API_BLOCK_KEY: PLTUTCo256Cg84A4lgZpa6mLsMqsX5qZzHTbD3Q2YbbRm5dejA9NGIufbhHkHcbjrPCsNt89W

  subscriber:
    container_name: subscriber
    image: gidyon/subscriber:v2
    command: ["--config-file", "/app/configs/config.yml"]
    depends_on:
      - "mysql"
    deploy:
      replicas: 1
    volumes:
      - ./configs/subscriber.config.yaml:/app/configs/config.yml
    environment:
      JWT_SIGNING_KEY: QFyvRWu7CeoHl6VS54ACvc27B7acfKCYWRLz7T8vSyBMOUA3VbKG9G1nLgsOmV9gryrTlkpKN357fcM0C81NsJ0ROHa4Jx8ps
      API_HASH_KEY: hmpVpI2nyiMhYIqLQlNfcL6QD37IOX1CklyU6TmVTy8hfbhblYUnKrHh4S93S2zORhmF2E3e6xDMLH5Dps0lM8XCQsV8cSP
      API_BLOCK_KEY: PLTUTCo256Cg84A4lgZpa6mLsMqsX5qZzHTbD3Q2YbbRm5dejA9NGIufbhHkHcbjrPCsNt89W
    
  channel:
    container_name: channel
    image: gidyon/channel:v2
    command: ["--config-file", "/app/configs/config.yml"]
    depends_on:
      - "mysql"
    deploy:
      replicas: 1
    volumes:
      - ./configs/channel.config.yaml:/app/configs/config.yml
    environment:
      JWT_SIGNING_KEY: QFyvRWu7CeoHl6VS54ACvc27B7acfKCYWRLz7T8vSyBMOUA3VbKG9G1nLgsOmV9gryrTlkpKN357fcM0C81NsJ0ROHa4Jx8ps
      API_HASH_KEY: hmpVpI2nyiMhYIqLQlNfcL6QD37IOX1CklyU6TmVTy8hfbhblYUnKrHh4S93S2zORhmF2E3e6xDMLH5Dps0lM8XCQsV8cSP
      API_BLOCK_KEY: PLTUTCo256Cg84A4lgZpa6mLsMqsX5qZzHTbD3Q2YbbRm5dejA9NGIufbhHkHcbjrPCsNt89W

  sms:
    container_name: sms
    image: gidyon/messaging-sms:v2
    command: ["--config-file", "/app/configs/config.yml"]
    deploy:
      replicas: 1
    volumes:
      - ./configs/sms.config.yaml:/app/configs/config.yml
    environment:
      JWT_SIGNING_KEY: QFyvRWu7CeoHl6VS54ACvc27B7acfKCYWRLz7T8vSyBMOUA3VbKG9G1nLgsOmV9gryrTlkpKN357fcM0C81NsJ0ROHa4Jx8ps

# secrets:
#   firebase_creds:
#     file: ./firebase.creds.json
#   jwt_signing_key:
#     file: ./jwtkey

networks:
  frontend-bridge:
    external: true
