serviceName: CHANNEL API
httpPort: 80
logLevel: 2
security:
  insecure: true
databases:
- required: true
  type: sqlDatabase
  address: mysql:3306
  user: root
  schema: machama
  password: hakty11
  metadata:
    name: sqlWrites
    dialect: mysql
    orm: gorm
- required: true
  type: sqlDatabase
  address: mysql:3306
  user: root
  schema: machama
  password: hakty11
  metadata:
    name: sqlReads
    dialect: mysql
    orm: gorm