serviceName: MESSAGING API
httpPort: 80
logLevel: 1
security:
  insecure: true
databases:
- required: true
  type: sqlDatabase
  address: mysql:3306
  user: root
  schema: machama
  password: hakty11
  metadata:
    name: sqlWrites
    dialect: mysql
    orm: gorm
- required: true
  type: sqlDatabase
  address: mysql:3306
  user: root
  schema: machama
  password: hakty11
  metadata:
    name: sqlReads
    dialect: mysql
    orm: gorm
externalServices:
- name: sms
  required: true
  address: sms:8080
  insecure: true
- name: emailing
  required: true
  address: emailing:8080
  insecure: true
- name: pusher
  required: true
  address: pusher:8080
  insecure: true
- name: call
  required: true
  address: call:8080
  insecure: true
- name: subscriber
  required: true
  address: subscriber:8080
  insecure: true